### ISSUE TITLE
package manager?

### ISSUE THREAD

**Issue by justinmk** [tarao/evil-plugins#3]
This doesn't seem to be available on any emacs package archive. Would you consider publishing on MELPA? http://melpa.milkbox.net/

**Comment by tarao** [comment]
I'm not going to maintain MELPA repo for evil-plugins since I never use MELPA. (I'm using [el-get](https://github.com/dimitri/el-get).) But I don't prevent someone from publishing my elisp packages on MELPA. There are some packages already published by someone else e.g. [anything-git-files](https://github.com/tarao/anything-git-files-el), [term+](https://github.com/tarao/term-plus-el).

Anyway, there is some work need to be done to publish evil-plugins on MELPA.
1. Some package headers (especially `Package-Requires`) must be provided for MELPA
   - Patches are welcome!
2. Some other packages required by evil-plugins need to be published on MELPA
   - e.g. evil-mode-line.el and evil-relative-linum.el depend on [mode-line-color.el](https://github.com/tarao/elisp/blob/master/mode-line-color.el) and [linum+.el](https://github.com/tarao/elisp/blob/master/linum%2B.el) respectively
